project:
  type: website
  output-dir: docs
  pre-render:
    - scripts/update-assignment-dates.R
    - scripts/hide-future-assignments.R
  render:
    - index.qmd
    - syllabus.qmd
    - class/*.qmd
    - reading/*.qmd
website:
  title: "Stat 892: TA Prep and Writing in Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.pdf
        text: Syllabus
  google-analytics: "G-LY19SLYGBW"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  cache: true
  freeze: true  # never re-render during project render
